# Generated by Django 5.1 on 2024-09-11 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_cart_quantity_cartitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='Cart',
            new_name='cart',
        ),
    ]
