# Generated by Django 5.1 on 2024-09-12 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_cart_quantity_delete_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='totals',
            field=models.IntegerField(default=1),
        ),
    ]
